name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Configure and start Apache server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install Apache2
            sudo apt-get update -y
            sudo apt-get install -y apache2
            
            # Start and enable Apache service
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Move deployed files to the correct directory
            sudo mv ~/$(basename ${{ secrets.TARGET_DIR }})/* /var/www/html/
            
            # Set correct permissions for the files
            sudo chmod -R 755 /var/www/html
